version: '3'

services:
  app:
    build: ./bot
    command: npm run start
    volumes:
      - ./bot:/usr/src/app
    networks:
      - cardapio-bot
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - data-volume:/data/db
    networks:
      - cardapio-bot

volumes:
  data-volume:

networks:
  cardapio-bot: